name: Bug Report
description: Report a bug
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Install package
        2. Run ...
        3. See error
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12"
    validations:
      required: true
